spring:
  application:
    name: gateway

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

app:
  allowed-origin: "${ALLOWED_ORIGIN}"
# eureka:
#   client:
#     service-url:
#       defaultZone: http://eureka-server:8761/eureka/

