spring:
  application:
    name: chat-service
  threads:
    virtual:
      enabled: true
  grpc:
    server:
      port: 9090

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  sql:
    init:
      mode: always

jwt:
  secret: ${JWT_SECRET}
  accessTokenExpirationMs: ${JWT_EXPIRATION_ACCESS_TOKEN}
  refreshTokenExpirationMs: ${JWT_EXPIRATION_REFRESH_TOKEN}

common:
  jwt:
    enabled: true
  exception:
    handler:
      enabled: true