spring:
  application:
    name: chat-service
  threads:
    virtual:
      enabled: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  sql:
    init:
      mode: always

jwt:
  secret: ${JWT_SECRET:mySecretKey}
  accessTokenExpirationMs: 86400000 # 24 hours
  refreshTokenExpirationMs: 604800000 # 7 days

common:
  jwt:
    enabled: true
  exception:
    handler:
      enabled: true