server:
  port: 8082
spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:postgresql://db:5432/${POSTGRES_DB_CHAT}
    username: ${POSTGRES_USER_CHAT}
    password: ${POSTGRES_PASSWORD_CHAT}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: rabbitmq
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    port: ${RABBITMQ_PORT}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@eureka:8761/eureka/
