spring:
  application:
    name: ai-service
  threads:
    virtual:
      enabled: true
  cloud:
    discovery:
      enabled: true
  grpc:
    client:
      chat-service:
       address: "dns:///chat-service:9090"
       negotiation-type: plaintext
       default-load-balancing-policy: round_robin
       enable-retry: true

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: false
    hostname: ai-service

jwt:
  secret: ${JWT_SECRET}
  accessTokenExpirationMs: ${JWT_EXPIRATION_ACCESS_TOKEN}
  refreshTokenExpirationMs: ${JWT_EXPIRATION_REFRESH_TOKEN}

common:
  jwt:
    enabled: true
  exception:
    handler:
      enabled: true