name: Pre-commit checks

on:
  pull_request:
  push:
    branches: [main,dev]

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      # 1 checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # intialize python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # install dependencies
      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pip install pytest
          pip install -r api/requirements.txt

      # cache
      - name: Setup pre-commit cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-precommit-

      # run pre-commit checks again
      - name: Run pre-commit hooks
        run: pre-commit run --all-files --show-diff-on-failure
